# Generated by Django 3.2.9 on 2021-12-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_developer_message_skill'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
